In [1]:
import csv
import os
import sys
import numpy as np
import torch
import pickle
import copy
from logging import Logger
from typing import List
from tqdm import trange
from torch.optim.lr_scheduler import ExponentialLR

In [2]:
# cd to chempropBayes
%cd '/Users/georgelamb/Documents/GitHub/chempropBayes'
from chemprop.train.run_training import run_training
from chemprop.args import TrainArgs
from chemprop.data.utils import get_class_sizes, get_data, get_task_names, split_data

/Users/georgelamb/Documents/GitHub/chempropBayes


In [3]:
args = TrainArgs()
args.from_dict({
    'dataset_type': 'regression',
    'data_path': '/Users/georgelamb/Documents/GitHub/chempropBayes/data/QM9.csv'
})

# location for model checkpoints to be saved
args.save_dir = '/Users/georgelamb/Documents/GitHub/chempropBayes/log'

args.seed = 0 # data seed
args.max_data_size = 50000
args.features_path = None
args.features_generator = None
args.split_type = 'scaffold_balanced'
args.split_sizes = (0.64, 0.16, 0.2)
args.metric = 'mae'
args.pytorch_seed = 0 # initial weights
args.atom_messages = False
args.undirected = False
args.bias = False
args.hidden_size = 500
args.depth = 5
args.ffn_hidden_size = args.hidden_size
args.ffn_num_layers = 3
args.activation = 'ReLU'
args.ensemble_size = 1
args.samples = 1
args.log_frequency = 640

In [4]:
# MAP
args.epochs = 100
args.init_log_noise = -2

args.warmup_epochs = 2.0
args.init_lr = 1e-4
args.max_lr = 1e-3
args.final_lr = 1e-4

args.wandb_name = 'MAP'

In [5]:
args.weight_decay = 0.01
results_MAP = run_training(args)

0it [00:00, ?it/s]

Command line
python /Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py -f /Users/georgelamb/Library/Jupyter/runtime/kernel-4813dbc2-0976-47a7-8cac-ceb3ea28407e.json
Args
{'activation': 'ReLU',
 'atom_messages': False,
 'batch_size_gp': 100,
 'batch_size_sgld': 50,
 'bbp': False,
 'bias': False,
 'block': True,
 'burnin_epochs': 10,
 'c_swag': 0,
 'cache_cutoff': 10000,
 'class_balance': False,
 'config_path': None,
 'cov_mat': False,
 'crossval_index_dir': None,
 'crossval_index_file': None,
 'crossval_index_sets': None,
 'data_path': '/Users/georgelamb/Documents/GitHub/chempropBayes/data/QM9.csv',
 'dataset_type': 'regression',
 'depth': 5,
 'dropout': 0.0,
 'dropout_FFNonly': False,
 'ensemble_size': 1,
 'epochs': 100,
 'epochs_gp': 100,
 'epochs_swag': 0,
 'features_generator': None,
 'features_only': False,
 'features_path': None,
 'features_size': None,
 'ffn_hidden_size': 500,
 'ffn_num_layers': 3,
 'final_lr': 0.0001,
 'final_lr_gp': 0.0001,
 'folds_file':

39893it [00:00, 79691.95it/s] 
  4%|▍         | 1994/50000 [00:00<00:02, 19939.35it/s]

Number of tasks = 12
Splitting data with seed 0


100%|██████████| 50000/50000 [00:04<00:00, 11467.92it/s]


Total size = 50,000 | train size = 32,000 | val size = 8,000 | test size = 10,000
Fitting scaler
Building model 0
MoleculeModel(
  (encoder): MPN(
    (encoder): MPNEncoder(
      (dropout_layer): Dropout(p=0.0, inplace=False)
      (act_func): ReLU()
      (W_i): Linear(in_features=147, out_features=500, bias=False)
      (W_h): Linear(in_features=500, out_features=500, bias=False)
      (W_o): Linear(in_features=633, out_features=500, bias=True)
    )
  )
  (ffn): Sequential(
    (0): Dropout(p=0.0, inplace=False)
    (1): Linear(in_features=500, out_features=500, bias=True)
    (2): ReLU()
    (3): Dropout(p=0.0, inplace=False)
    (4): Linear(in_features=500, out_features=500, bias=True)
    (5): ReLU()
    (6): Dropout(p=0.0, inplace=False)
    (7): Linear(in_features=500, out_features=12, bias=True)
  )
)
Number of parameters = 1,147,524


Epoch 0
Loss = 7.9719e+01, PNorm = 41.9207, GNorm = 661.8070, lr_0 = 5.5070e-04, lr_1 = 5.5070e-04, lr_2 = 5.5070e-04
Validation mae = 13.798800
Epoch 1
Loss = 1.8579e+01, PNorm = 41.2425, GNorm = 282.6487, lr_0 = 9.9996e-04, lr_1 = 9.9996e-04, lr_2 = 9.9996e-04
Validation mae = 10.841062
Epoch 2
Loss = -8.2142e-02, PNorm = 40.3308, GNorm = 198.7011, lr_0 = 9.7674e-04, lr_1 = 9.7674e-04, lr_2 = 9.7674e-04
Validation mae = 9.521616
Epoch 3


Process Process-50:
Process Process-53:
Process Process-54:
Process Process-51:
Process Process-49:
Process Process-56:
Process Process-55:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.7/multiprocessing/process.py", line 300, in _bootstrap
    util._exit_function()
  File "/Applications/anaconda3/lib/python3.7/multiprocessing/process.py", line 300, in _bootstrap
    util._exit_function()
  File "/Applications/anaconda3/lib/python3.7/multiprocessing/process.py", line 300, in _bootstrap
    util._exit_function()
  File "/Applications/anaconda3/lib/python3.7/multiprocessing/process.py", line 300, in _bootstrap
    util._exit_function()
  File "/Applications/anaconda3/lib/python3.7/multiprocessing/process.py", line 300, in _bootstrap
    util._exit_f

KeyboardInterrupt: 

Error in callback <function _init_jupyter.<locals>.cleanup at 0x7f883f79b560> (for post_run_cell):


KeyboardInterrupt: 

Weight decay of 0.01

In [5]:
args.weight_decay = 0.01
results_MAP = run_training(args)

5903it [00:00, 59027.10it/s]

Command line
python /Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py -f /Users/georgelamb/Library/Jupyter/runtime/kernel-3ce28114-5e5a-455d-a29b-0c200a224367.json
Args
{'activation': 'ReLU',
 'atom_messages': False,
 'batch_size_gp': 100,
 'batch_size_sgld': 50,
 'bbp': False,
 'bias': False,
 'block': True,
 'burnin_epochs': 10,
 'c_swag': 0,
 'cache_cutoff': 10000,
 'class_balance': False,
 'config_path': None,
 'cov_mat': False,
 'crossval_index_dir': None,
 'crossval_index_file': None,
 'crossval_index_sets': None,
 'data_path': '/Users/georgelamb/Documents/GitHub/chempropBayes/data/QM9.csv',
 'dataset_type': 'regression',
 'depth': 5,
 'dropout': 0.0,
 'dropout_FFNonly': False,
 'ensemble_size': 1,
 'epochs': 100,
 'epochs_gp': 100,
 'epochs_swag': 0,
 'features_generator': None,
 'features_only': False,
 'features_path': None,
 'features_size': None,
 'ffn_hidden_size': 500,
 'ffn_num_layers': 3,
 'final_lr': 0.0001,
 'final_lr_gp': 0.0001,
 'folds_file':

49476it [00:00, 88270.38it/s]
  4%|▍         | 1991/50000 [00:00<00:02, 19900.06it/s]

Number of tasks = 12
Splitting data with seed 0


100%|██████████| 50000/50000 [00:04<00:00, 11510.29it/s]


Total size = 50,000 | train size = 32,000 | val size = 8,000 | test size = 10,000
Fitting scaler
Building model 0
MoleculeModel(
  (encoder): MPN(
    (encoder): MPNEncoder(
      (dropout_layer): Dropout(p=0.0, inplace=False)
      (act_func): ReLU()
      (W_i): Linear(in_features=147, out_features=500, bias=False)
      (W_h): Linear(in_features=500, out_features=500, bias=False)
      (W_o): Linear(in_features=633, out_features=500, bias=True)
    )
  )
  (ffn): Sequential(
    (0): Dropout(p=0.0, inplace=False)
    (1): Linear(in_features=500, out_features=500, bias=True)
    (2): ReLU()
    (3): Dropout(p=0.0, inplace=False)
    (4): Linear(in_features=500, out_features=500, bias=True)
    (5): ReLU()
    (6): Dropout(p=0.0, inplace=False)
    (7): Linear(in_features=500, out_features=12, bias=True)
  )
)
Number of parameters = 1,147,524
Epoch 0
Loss = 1.5944e+00, PNorm = 41.9207, GNorm = 661.8070, lr_0 = 5.5070e-04, lr_1 = 5.5070e-04, lr_2 = 5.5070e-04
Parameter containing:
tens

Validation mae = 3.665068
Epoch 24
Loss = -3.2856e-01, PNorm = 27.1110, GNorm = 59.0229, lr_0 = 5.8249e-04, lr_1 = 5.8249e-04, lr_2 = 5.8249e-04
Parameter containing:
tensor([-0.7251, -1.9034, -1.3880, -2.0041, -1.7145, -1.6125, -2.3558, -1.8251,
        -2.0819, -2.0811, -2.0809, -2.0811], requires_grad=True)
Validation mae = 3.617521
Epoch 25
Loss = -3.0456e-01, PNorm = 27.6068, GNorm = 59.5624, lr_0 = 5.6897e-04, lr_1 = 5.6897e-04, lr_2 = 5.6897e-04
Parameter containing:
tensor([-0.7089, -1.8806, -1.3593, -1.9620, -1.6813, -1.5939, -2.3448, -1.7998,
        -2.0586, -2.0576, -2.0574, -2.0573], requires_grad=True)
Validation mae = 4.015478
Epoch 26
Loss = -3.3729e-01, PNorm = 27.1543, GNorm = 95.2865, lr_0 = 5.5575e-04, lr_1 = 5.5575e-04, lr_2 = 5.5575e-04
Parameter containing:
tensor([-0.7279, -1.9261, -1.4002, -2.0273, -1.7368, -1.6262, -2.3813, -1.8483,
        -2.1037, -2.1030, -2.1027, -2.1026], requires_grad=True)
Validation mae = 3.715247
Epoch 27
Loss = -3.3862e-01, PNorm = 2

Validation mae = 2.985512
Epoch 51
Loss = -4.0177e-01, PNorm = 27.3235, GNorm = 44.9888, lr_0 = 3.0887e-04, lr_1 = 3.0887e-04, lr_2 = 3.0887e-04
Parameter containing:
tensor([-0.8668, -2.2717, -1.6524, -2.3054, -2.0299, -1.8661, -2.7438, -2.1720,
        -2.4967, -2.4966, -2.4964, -2.4961], requires_grad=True)
Validation mae = 2.935012
Epoch 52
Loss = -4.2389e-01, PNorm = 27.3111, GNorm = 75.7853, lr_0 = 3.0170e-04, lr_1 = 3.0170e-04, lr_2 = 3.0170e-04
Parameter containing:
tensor([-0.8751, -2.2896, -1.6673, -2.3241, -2.0451, -1.8766, -2.7590, -2.1882,
        -2.5195, -2.5194, -2.5193, -2.5190], requires_grad=True)
Validation mae = 3.132162
Epoch 53
Loss = -4.2266e-01, PNorm = 27.2690, GNorm = 99.5230, lr_0 = 2.9469e-04, lr_1 = 2.9469e-04, lr_2 = 2.9469e-04
Parameter containing:
tensor([-0.8813, -2.3048, -1.6825, -2.3426, -2.0573, -1.8873, -2.7718, -2.2012,
        -2.5377, -2.5376, -2.5376, -2.5373], requires_grad=True)
Validation mae = 2.795774
Epoch 54
Loss = -4.1519e-01, PNorm = 2

Validation mae = 2.658275
Epoch 78
Loss = -4.7511e-01, PNorm = 27.2950, GNorm = 79.9496, lr_0 = 1.6378e-04, lr_1 = 1.6378e-04, lr_2 = 1.6378e-04
Parameter containing:
tensor([-0.9967, -2.5206, -1.9281, -2.6003, -2.3556, -2.0758, -2.9673, -2.4052,
        -2.7859, -2.7859, -2.7859, -2.7857], requires_grad=True)
Validation mae = 2.535998
Epoch 79
Loss = -4.7867e-01, PNorm = 27.2811, GNorm = 95.4715, lr_0 = 1.5998e-04, lr_1 = 1.5998e-04, lr_2 = 1.5998e-04
Parameter containing:
tensor([-1.0019, -2.5263, -1.9409, -2.6121, -2.3712, -2.0831, -2.9726, -2.4113,
        -2.7923, -2.7923, -2.7923, -2.7922], requires_grad=True)
Validation mae = 2.569717
Epoch 80
Loss = -4.8160e-01, PNorm = 27.2778, GNorm = 75.1990, lr_0 = 1.5626e-04, lr_1 = 1.5626e-04, lr_2 = 1.5626e-04
Parameter containing:
tensor([-1.0047, -2.5323, -1.9488, -2.6241, -2.3833, -2.0898, -2.9779, -2.4173,
        -2.7990, -2.7990, -2.7990, -2.7988], requires_grad=True)
Validation mae = 2.513182
Epoch 81
Loss = -4.7210e-01, PNorm = 2