In [2]:
import csv
import os
import sys
import numpy as np
import torch
import pickle
import copy
from logging import Logger
from typing import List
from tqdm import trange
from torch.optim.lr_scheduler import ExponentialLR

In [3]:
# cd to chempropBayes
%cd '/Users/georgelamb/Documents/GitHub/chempropBayes'
from chemprop.train.run_training import run_training
from chemprop.args import TrainArgs
from chemprop.data.utils import get_class_sizes, get_data, get_task_names, split_data

/Users/georgelamb/Documents/GitHub/chempropBayes


In [4]:
!python scripts/map.py

working directory is:
/Users/georgelamb/Documents/GitHub/chempropBayes
is CUDA available?
False
Traceback (most recent call last):
  File "scripts/map.py", line 14, in <module>
    from chemprop.args import TrainArgs
  File "/Users/georgelamb/Documents/GitHub/chempropBayes/chemprop/__init__.py", line 1, in <module>
    import chemprop.data
  File "/Users/georgelamb/Documents/GitHub/chempropBayes/chemprop/data/__init__.py", line 1, in <module>
    from .data import MoleculeDatapoint, MoleculeDataset, MoleculeDataLoader
  File "/Users/georgelamb/Documents/GitHub/chempropBayes/chemprop/data/data.py", line 7, in <module>
    from rdkit import Chem
ModuleNotFoundError: No module named 'rdkit'


In [3]:
args = TrainArgs()
args.from_dict({
    'dataset_type': 'regression',
    'data_path': '/Users/georgelamb/Documents/GitHub/chempropBayes/data/QM9.csv'
})

# location for model checkpoints to be saved
args.save_dir = '/Users/georgelamb/Documents/GitHub/chempropBayes/log'

args.seed = 0 # data seed
args.max_data_size = 50000
args.features_path = None
args.features_generator = None
args.split_type = 'scaffold_balanced'
args.split_sizes = (0.64, 0.16, 0.2)
args.metric = 'mae'
args.pytorch_seed = 0 # initial weights
args.atom_messages = False
args.undirected = False
args.bias = False
args.hidden_size = 500
args.depth = 5
args.ffn_hidden_size = args.hidden_size
args.ffn_num_layers = 3
args.activation = 'ReLU'
args.ensemble_size = 1
args.samples = 1
args.log_frequency = 640

In [6]:
seeds = [0,1,2,3,4]
seeds[0]

0

Test new epochs scedule

In [4]:
args.init_lr = 1e-4
args.max_lr = 1e-3
args.final_lr = 1e-4

args.warmup_epochs = 2
args.noam_epochs = 5
args.epochs = 10

args.weight_decay = 0.01
args.wandb_name = 'dropout'
args.dropout = 0.05
args.wandb_name = 'dropout_flat'
results_drop = run_training(args)

0it [00:00, ?it/s]

Command line
python /Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py -f /Users/georgelamb/Library/Jupyter/runtime/kernel-9d40038a-489e-4e6d-979f-67adf649acda.json
Args
{'activation': 'ReLU',
 'atom_messages': False,
 'batch_size_gp': 100,
 'batch_size_sgld': 50,
 'bbp': False,
 'bias': False,
 'block': True,
 'burnin_epochs': 10,
 'c_swag': 0,
 'cache_cutoff': 10000,
 'class_balance': False,
 'config_path': None,
 'cov_mat': False,
 'crossval_index_dir': None,
 'crossval_index_file': None,
 'crossval_index_sets': None,
 'data_path': '/Users/georgelamb/Documents/GitHub/chempropBayes/data/QM9.csv',
 'dataset_type': 'regression',
 'depth': 5,
 'dropout': 0.05,
 'dropout_FFNonly': False,
 'ensemble_size': 1,
 'epochs': 10,
 'epochs_gp': 100,
 'epochs_swag': 0,
 'features_generator': None,
 'features_only': False,
 'features_path': None,
 'features_size': None,
 'ffn_hidden_size': 500,
 'ffn_num_layers': 3,
 'final_lr': 0.0001,
 'final_lr_gp': 0.0001,
 'folds_file':

48928it [00:00, 92581.41it/s] 
  7%|▋         | 3400/50000 [00:00<00:02, 17722.39it/s]

Number of tasks = 12
Splitting data with seed 0


100%|██████████| 50000/50000 [00:04<00:00, 11356.02it/s]


Total size = 50,000 | train size = 32,000 | val size = 8,000 | test size = 10,000
Fitting scaler
Building model 0
MoleculeModel(
  (encoder): MPN(
    (encoder): MPNEncoder(
      (dropout_layer): Dropout(p=0.05, inplace=False)
      (act_func): ReLU()
      (W_i): Linear(in_features=147, out_features=500, bias=False)
      (W_h): Linear(in_features=500, out_features=500, bias=False)
      (W_o): Linear(in_features=633, out_features=500, bias=True)
    )
  )
  (ffn): Sequential(
    (0): Dropout(p=0.05, inplace=False)
    (1): Linear(in_features=500, out_features=500, bias=True)
    (2): ReLU()
    (3): Dropout(p=0.05, inplace=False)
    (4): Linear(in_features=500, out_features=500, bias=True)
    (5): ReLU()
    (6): Dropout(p=0.05, inplace=False)
    (7): Linear(in_features=500, out_features=12, bias=True)
  )
)
Number of parameters = 1,147,524


Epoch 0
Loss = 8.8317e+01, PNorm = 43.8142, GNorm = 473.8693, lr_0 = 5.5070e-04, lr_1 = 5.5070e-04, lr_2 = 5.5070e-04
Validation mae = 14.524845
Epoch 1
Loss = 2.1073e+01, PNorm = 42.9205, GNorm = 181.2687, lr_0 = 9.9880e-04, lr_1 = 9.9880e-04, lr_2 = 9.9880e-04
Validation mae = 12.123371
Epoch 2
Loss = 1.7316e+00, PNorm = 41.8499, GNorm = 110.0326, lr_0 = 4.6360e-04, lr_1 = 4.6360e-04, lr_2 = 4.6360e-04
Validation mae = 8.924449
Epoch 3
Loss = -5.1705e+00, PNorm = 41.1278, GNorm = 76.5623, lr_0 = 2.1519e-04, lr_1 = 2.1519e-04, lr_2 = 2.1519e-04
Validation mae = 7.488042
Epoch 4
Loss = -7.4595e+00, PNorm = 40.7035, GNorm = 173.0434, lr_0 = 1.0000e-04, lr_1 = 1.0000e-04, lr_2 = 1.0000e-04
Validation mae = 6.608478
Epoch 5
Loss = -8.3182e+00, PNorm = 39.9029, GNorm = 136.6003, lr_0 = 1.0000e-04
Validation mae = 6.786297
Epoch 6
Loss = -9.1953e+00, PNorm = 39.2649, GNorm = 74.4282, lr_0 = 1.0000e-04
Validation mae = 6.565985
Epoch 7
Loss = -9.8172e+00, PNorm = 38.6639, GNorm = 132.4048, l

In [5]:
args.init_lr = 1e-4
args.max_lr = 1e-3
args.final_lr = 1e-4
args.warmup_epochs = 2
args.epochs = 100
args.weight_decay = 0.01
args.wandb_name = 'dropout'
args.dropout = 0.05
args.wandb_name = 'dropout_lowlearn'
results_drop = run_training(args)

0it [00:00, ?it/s]

Command line
python /Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py -f /Users/georgelamb/Library/Jupyter/runtime/kernel-94b25f5d-7c40-498a-bdd2-876b622339d9.json
Args
{'activation': 'ReLU',
 'atom_messages': False,
 'batch_size_gp': 100,
 'batch_size_sgld': 50,
 'bbp': False,
 'bias': False,
 'block': True,
 'burnin_epochs': 10,
 'c_swag': 0,
 'cache_cutoff': 10000,
 'class_balance': False,
 'config_path': None,
 'cov_mat': False,
 'crossval_index_dir': None,
 'crossval_index_file': None,
 'crossval_index_sets': None,
 'data_path': '/Users/georgelamb/Documents/GitHub/chempropBayes/data/QM9.csv',
 'dataset_type': 'regression',
 'depth': 5,
 'dropout': 0.05,
 'dropout_FFNonly': False,
 'ensemble_size': 1,
 'epochs': 100,
 'epochs_gp': 100,
 'epochs_swag': 0,
 'features_generator': None,
 'features_only': False,
 'features_path': None,
 'features_size': None,
 'ffn_hidden_size': 500,
 'ffn_num_layers': 3,
 'final_lr': 0.0001,
 'final_lr_gp': 0.0001,
 'folds_file'

47701it [00:00, 88134.79it/s] 
  4%|▍         | 1969/50000 [00:00<00:02, 19682.14it/s]

Number of tasks = 12
Splitting data with seed 0


100%|██████████| 50000/50000 [00:04<00:00, 11329.53it/s]


Total size = 50,000 | train size = 32,000 | val size = 8,000 | test size = 10,000
Fitting scaler
Building model 0
MoleculeModel(
  (encoder): MPN(
    (encoder): MPNEncoder(
      (dropout_layer): Dropout(p=0.05, inplace=False)
      (act_func): ReLU()
      (W_i): Linear(in_features=147, out_features=500, bias=False)
      (W_h): Linear(in_features=500, out_features=500, bias=False)
      (W_o): Linear(in_features=633, out_features=500, bias=True)
    )
  )
  (ffn): Sequential(
    (0): Dropout(p=0.05, inplace=False)
    (1): Linear(in_features=500, out_features=500, bias=True)
    (2): ReLU()
    (3): Dropout(p=0.05, inplace=False)
    (4): Linear(in_features=500, out_features=500, bias=True)
    (5): ReLU()
    (6): Dropout(p=0.05, inplace=False)
    (7): Linear(in_features=500, out_features=12, bias=True)
  )
)
Number of parameters = 1,147,524


Epoch 0
Loss = 8.8317e+01, PNorm = 43.8142, GNorm = 473.8693, lr_0 = 5.5070e-04, lr_1 = 5.5070e-04, lr_2 = 5.5070e-04
Parameter containing:
tensor([-1.8521, -1.8798, -1.8866, -1.9162, -1.8938, -1.8768, -1.9214, -1.8768,
        -1.8811, -1.8828, -1.8831, -1.8808], requires_grad=True)
Validation mae = 14.524845
Epoch 1
Loss = 2.1073e+01, PNorm = 42.9205, GNorm = 181.2687, lr_0 = 9.9996e-04, lr_1 = 9.9996e-04, lr_2 = 9.9996e-04
Parameter containing:
tensor([-1.6061, -1.7011, -1.6875, -1.7932, -1.7224, -1.6991, -1.7791, -1.6841,
        -1.6932, -1.6966, -1.6966, -1.6934], requires_grad=True)
Validation mae = 12.123371
Epoch 2
Loss = 2.1524e+00, PNorm = 41.5484, GNorm = 113.7046, lr_0 = 9.7674e-04, lr_1 = 9.7674e-04, lr_2 = 9.7674e-04
Parameter containing:
tensor([-1.3897, -1.5541, -1.5105, -1.6924, -1.5768, -1.5534, -1.6648, -1.5256,
        -1.5464, -1.5502, -1.5502, -1.5469], requires_grad=True)
Validation mae = 9.350208
Epoch 3
Loss = -4.9116e+00, PNorm = 39.8327, GNorm = 74.4505, lr_

Validation mae = 4.582073
Epoch 27
Loss = -1.3619e+01, PNorm = 27.1677, GNorm = 65.3718, lr_0 = 5.4285e-04, lr_1 = 5.4285e-04, lr_2 = 5.4285e-04
Parameter containing:
tensor([-0.6411, -1.7056, -1.2429, -1.7666, -1.5377, -1.4447, -2.0061, -1.6083,
        -1.8718, -1.8718, -1.8719, -1.8718], requires_grad=True)
Validation mae = 5.735339
Epoch 28
Loss = -1.3557e+01, PNorm = 27.1505, GNorm = 140.8432, lr_0 = 5.3024e-04, lr_1 = 5.3024e-04, lr_2 = 5.3024e-04
Parameter containing:
tensor([-0.6522, -1.7079, -1.2500, -1.7860, -1.5438, -1.4513, -2.0101, -1.6093,
        -1.8791, -1.8791, -1.8792, -1.8792], requires_grad=True)
Validation mae = 4.388466
Epoch 29
Loss = -1.3893e+01, PNorm = 27.1541, GNorm = 27.7209, lr_0 = 5.1793e-04, lr_1 = 5.1793e-04, lr_2 = 5.1793e-04
Parameter containing:
tensor([-0.6550, -1.7229, -1.2598, -1.7954, -1.5616, -1.4644, -2.0260, -1.6288,
        -1.8977, -1.8976, -1.8976, -1.8977], requires_grad=True)
Validation mae = 3.995385
Epoch 30
Loss = -1.3856e+01, PNorm = 

Validation mae = 3.611217
Epoch 54
Loss = -1.5925e+01, PNorm = 26.6305, GNorm = 148.0184, lr_0 = 2.8785e-04, lr_1 = 2.8785e-04, lr_2 = 2.8785e-04
Parameter containing:
tensor([-0.7125, -1.9017, -1.3744, -1.9314, -1.6976, -1.5884, -2.1929, -1.7953,
        -2.1259, -2.1259, -2.1259, -2.1258], requires_grad=True)
Validation mae = 3.107161
Epoch 55
Loss = -1.5935e+01, PNorm = 26.6046, GNorm = 27.9806, lr_0 = 2.8117e-04, lr_1 = 2.8117e-04, lr_2 = 2.8117e-04
Parameter containing:
tensor([-0.7148, -1.9070, -1.3771, -1.9333, -1.7053, -1.5951, -2.1983, -1.8023,
        -2.1317, -2.1317, -2.1317, -2.1316], requires_grad=True)
Validation mae = 3.227501
Epoch 56
Loss = -1.6102e+01, PNorm = 26.5143, GNorm = 45.2163, lr_0 = 2.7464e-04, lr_1 = 2.7464e-04, lr_2 = 2.7464e-04
Parameter containing:
tensor([-0.7210, -1.9155, -1.3902, -1.9420, -1.7173, -1.5980, -2.2051, -1.8076,
        -2.1413, -2.1412, -2.1413, -2.1412], requires_grad=True)
Validation mae = 3.298969
Epoch 57
Loss = -1.6205e+01, PNorm = 

Validation mae = 2.801855
Epoch 81
Loss = -1.7434e+01, PNorm = 26.2076, GNorm = 95.0756, lr_0 = 1.5264e-04, lr_1 = 1.5264e-04, lr_2 = 1.5264e-04
Parameter containing:
tensor([-0.7559, -2.0341, -1.4633, -2.0256, -1.8071, -1.6780, -2.3068, -1.9133,
        -2.2944, -2.2945, -2.2945, -2.2944], requires_grad=True)
Validation mae = 2.833710
Epoch 82
Loss = -1.7517e+01, PNorm = 26.1758, GNorm = 55.9644, lr_0 = 1.4909e-04, lr_1 = 1.4909e-04, lr_2 = 1.4909e-04
Parameter containing:
tensor([-0.7562, -2.0373, -1.4611, -2.0295, -1.8084, -1.6812, -2.3107, -1.9162,
        -2.3003, -2.3003, -2.3003, -2.3002], requires_grad=True)
Validation mae = 2.907340
Epoch 83
Loss = -1.7468e+01, PNorm = 26.1961, GNorm = 44.6532, lr_0 = 1.4563e-04, lr_1 = 1.4563e-04, lr_2 = 1.4563e-04
Parameter containing:
tensor([-0.7586, -2.0408, -1.4664, -2.0323, -1.8126, -1.6831, -2.3142, -1.9192,
        -2.3044, -2.3044, -2.3044, -2.3044], requires_grad=True)
Validation mae = 2.966983
Epoch 84
Loss = -1.7523e+01, PNorm = 2

Dropout with lower lr

In [ ]:
args.init_lr = 1e-4
args.max_lr = 1e-3
args.final_lr = 1e-5
args.warmup_epochs = 10.0
args.epochs = 300
args.weight_decay = 0.01
args.wandb_name = 'dropout'
args.dropout = 0.1
args.wandb_name = 'dropout_lowlearn'
results_drop = run_training(args)

0it [00:00, ?it/s]

Command line
python /Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py -f /Users/georgelamb/Library/Jupyter/runtime/kernel-94b25f5d-7c40-498a-bdd2-876b622339d9.json
Args
{'activation': 'ReLU',
 'atom_messages': False,
 'batch_size_gp': 100,
 'batch_size_sgld': 50,
 'bbp': False,
 'bias': False,
 'block': True,
 'burnin_epochs': 10,
 'c_swag': 0,
 'cache_cutoff': 10000,
 'class_balance': False,
 'config_path': None,
 'cov_mat': False,
 'crossval_index_dir': None,
 'crossval_index_file': None,
 'crossval_index_sets': None,
 'data_path': '/Users/georgelamb/Documents/GitHub/chempropBayes/data/QM9.csv',
 'dataset_type': 'regression',
 'depth': 5,
 'dropout': 0.1,
 'dropout_FFNonly': False,
 'ensemble_size': 1,
 'epochs': 300,
 'epochs_gp': 100,
 'epochs_swag': 0,
 'features_generator': None,
 'features_only': False,
 'features_path': None,
 'features_size': None,
 'ffn_hidden_size': 500,
 'ffn_num_layers': 3,
 'final_lr': 1e-05,
 'final_lr_gp': 0.0001,
 'folds_file': 

48320it [00:00, 89093.63it/s] 
  4%|▍         | 1960/50000 [00:00<00:02, 19595.49it/s]

Number of tasks = 12
Splitting data with seed 0


100%|██████████| 50000/50000 [00:04<00:00, 11237.24it/s]


Total size = 50,000 | train size = 32,000 | val size = 8,000 | test size = 10,000
Fitting scaler
Building model 0
MoleculeModel(
  (encoder): MPN(
    (encoder): MPNEncoder(
      (dropout_layer): Dropout(p=0.1, inplace=False)
      (act_func): ReLU()
      (W_i): Linear(in_features=147, out_features=500, bias=False)
      (W_h): Linear(in_features=500, out_features=500, bias=False)
      (W_o): Linear(in_features=633, out_features=500, bias=True)
    )
  )
  (ffn): Sequential(
    (0): Dropout(p=0.1, inplace=False)
    (1): Linear(in_features=500, out_features=500, bias=True)
    (2): ReLU()
    (3): Dropout(p=0.1, inplace=False)
    (4): Linear(in_features=500, out_features=500, bias=True)
    (5): ReLU()
    (6): Dropout(p=0.1, inplace=False)
    (7): Linear(in_features=500, out_features=12, bias=True)
  )
)
Number of parameters = 1,147,524


Epoch 0
Loss = 1.0795e+02, PNorm = 44.7761, GNorm = 498.2163, lr_0 = 1.9014e-04, lr_1 = 1.9014e-04, lr_2 = 1.9014e-04
Parameter containing:
tensor([-1.9276, -1.9380, -1.9440, -1.9527, -1.9432, -1.9347, -1.9573, -1.9376,
        -1.9390, -1.9399, -1.9401, -1.9390], requires_grad=True)
Validation mae = 15.306404
Epoch 1
Loss = 4.0580e+01, PNorm = 44.2114, GNorm = 793.2010, lr_0 = 2.8014e-04, lr_1 = 2.8014e-04, lr_2 = 2.8014e-04
Parameter containing:
tensor([-1.8297, -1.8653, -1.8630, -1.8955, -1.8708, -1.8625, -1.8987, -1.8596,
        -1.8624, -1.8646, -1.8648, -1.8631], requires_grad=True)
Validation mae = 14.088319
Epoch 2
Loss = 2.2387e+01, PNorm = 43.7801, GNorm = 287.0897, lr_0 = 3.7014e-04, lr_1 = 3.7014e-04, lr_2 = 3.7014e-04
Parameter containing:
tensor([-1.7101, -1.7715, -1.7593, -1.8296, -1.7830, -1.7704, -1.8195, -1.7579,
        -1.7632, -1.7664, -1.7661, -1.7639], requires_grad=True)
Validation mae = 11.727799
Epoch 3
Loss = 9.8405e+00, PNorm = 43.1617, GNorm = 128.8608, lr

requests_with_retry encountered retryable exception: ('Connection aborted.', OSError("(60, 'ETIMEDOUT')")). args: ('https://api.wandb.ai/files/georgelamb19/chempropBayes/12c1a9eu/file_stream',), kwargs: {'json': {'files': {'output.log': {'offset': 71, 'content': ['2020-08-15T12:24:18.468910 Validation mae = 6.258801\n', '2020-08-15T12:24:18.515158 Epoch 12\n']}, 'wandb-events.jsonl': {'offset': 32, 'content': ['{"system.cpu": 90.73, "system.memory": 54.73, "system.disk": 2.5, "system.proc.memory.availableMB": 7418.16, "system.proc.memory.rssMB": 789.71, "system.proc.memory.percent": 4.82, "system.proc.cpu.threads": 40.0, "system.network.sent": 20641792, "system.network.recv": 23621632, "_wandb": true, "_timestamp": 1597494286, "_runtime": 1017}\n']}, 'wandb-history.jsonl': {'offset': 11, 'content': ['{"Negative log likelihood (scaled)": -8.465883003268392, "Validation MAE": 6.2588008334322325, "_runtime": 989.7063961029053, "_timestamp": 1597494258.469449, "_step": 11}\n']}, 'wandb-sum

Loss = -8.4740e+00, PNorm = 29.2877, GNorm = 51.7802, lr_0 = 9.5345e-04, lr_1 = 9.5345e-04, lr_2 = 9.5345e-04
Parameter containing:
tensor([-0.5828, -1.2179, -1.0112, -1.4829, -1.2619, -1.1170, -1.5138, -1.1511,
        -1.2942, -1.2948, -1.2947, -1.2935], requires_grad=True)
Validation mae = 7.213547
Epoch 13
Loss = -8.6025e+00, PNorm = 28.7458, GNorm = 41.1048, lr_0 = 9.3843e-04, lr_1 = 9.3843e-04, lr_2 = 9.3843e-04
Parameter containing:
tensor([-0.5588, -1.2307, -1.0106, -1.4709, -1.2560, -1.1092, -1.5310, -1.1602,
        -1.3089, -1.3095, -1.3094, -1.3087], requires_grad=True)
Validation mae = 6.020877
Epoch 14
Loss = -9.0961e+00, PNorm = 28.3908, GNorm = 54.4007, lr_0 = 9.2365e-04, lr_1 = 9.2365e-04, lr_2 = 9.2365e-04
Parameter containing:
tensor([-0.5407, -1.2688, -1.0252, -1.4994, -1.2708, -1.1338, -1.5735, -1.2031,
        -1.3659, -1.3664, -1.3668, -1.3661], requires_grad=True)
Validation mae = 7.741418
Epoch 15
Loss = -8.8616e+00, PNorm = 28.1543, GNorm = 57.5438, lr_0 = 9.0

Validation mae = 4.051579
Epoch 39
Loss = -1.2019e+01, PNorm = 27.4080, GNorm = 64.5672, lr_0 = 6.2100e-04, lr_1 = 6.2100e-04, lr_2 = 6.2100e-04
Parameter containing:
tensor([-0.5874, -1.5782, -1.1328, -1.6458, -1.4243, -1.3440, -1.8260, -1.4769,
        -1.7554, -1.7554, -1.7554, -1.7554], requires_grad=True)
Validation mae = 5.038443
Epoch 40
Loss = -1.1975e+01, PNorm = 27.5408, GNorm = 52.1379, lr_0 = 6.1122e-04, lr_1 = 6.1122e-04, lr_2 = 6.1122e-04
Parameter containing:
tensor([-0.5846, -1.5765, -1.1466, -1.6552, -1.4316, -1.3448, -1.8359, -1.4765,
        -1.7467, -1.7467, -1.7467, -1.7467], requires_grad=True)
Validation mae = 4.301761
Epoch 41
Loss = -1.2431e+01, PNorm = 27.2972, GNorm = 53.7309, lr_0 = 6.0159e-04, lr_1 = 6.0159e-04, lr_2 = 6.0159e-04
Parameter containing:
tensor([-0.5899, -1.6028, -1.1556, -1.6577, -1.4497, -1.3597, -1.8562, -1.5009,
        -1.7755, -1.7756, -1.7755, -1.7755], requires_grad=True)
Validation mae = 4.015901
Epoch 42
Loss = -1.2329e+01, PNorm = 2

Dropout test

In [5]:
args.warmup_epochs = 10.0
args.epochs = 300
args.weight_decay = 0.01
args.wandb_name = 'dropout'
args.dropout = 0.1
results_drop = run_training(args)

0it [00:00, ?it/s]

Command line
python /Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py -f /Users/georgelamb/Library/Jupyter/runtime/kernel-94b25f5d-7c40-498a-bdd2-876b622339d9.json
Args
{'activation': 'ReLU',
 'atom_messages': False,
 'batch_size_gp': 100,
 'batch_size_sgld': 50,
 'bbp': False,
 'bias': False,
 'block': True,
 'burnin_epochs': 10,
 'c_swag': 0,
 'cache_cutoff': 10000,
 'class_balance': False,
 'config_path': None,
 'cov_mat': False,
 'crossval_index_dir': None,
 'crossval_index_file': None,
 'crossval_index_sets': None,
 'data_path': '/Users/georgelamb/Documents/GitHub/chempropBayes/data/QM9.csv',
 'dataset_type': 'regression',
 'depth': 5,
 'dropout': 0.1,
 'dropout_FFNonly': False,
 'ensemble_size': 1,
 'epochs': 300,
 'epochs_gp': 100,
 'epochs_swag': 0,
 'features_generator': None,
 'features_only': False,
 'features_path': None,
 'features_size': None,
 'ffn_hidden_size': 500,
 'ffn_num_layers': 3,
 'final_lr': 0.0001,
 'final_lr_gp': 0.0001,
 'folds_file':

39088it [00:00, 78512.00it/s] 
  7%|▋         | 3362/50000 [00:00<00:02, 17518.95it/s]

Number of tasks = 12
Splitting data with seed 0


100%|██████████| 50000/50000 [00:04<00:00, 11445.49it/s]


Total size = 50,000 | train size = 32,000 | val size = 8,000 | test size = 10,000
Fitting scaler
Building model 0
MoleculeModel(
  (encoder): MPN(
    (encoder): MPNEncoder(
      (dropout_layer): Dropout(p=0.1, inplace=False)
      (act_func): ReLU()
      (W_i): Linear(in_features=147, out_features=500, bias=False)
      (W_h): Linear(in_features=500, out_features=500, bias=False)
      (W_o): Linear(in_features=633, out_features=500, bias=True)
    )
  )
  (ffn): Sequential(
    (0): Dropout(p=0.1, inplace=False)
    (1): Linear(in_features=500, out_features=500, bias=True)
    (2): ReLU()
    (3): Dropout(p=0.1, inplace=False)
    (4): Linear(in_features=500, out_features=500, bias=True)
    (5): ReLU()
    (6): Dropout(p=0.1, inplace=False)
    (7): Linear(in_features=500, out_features=12, bias=True)
  )
)
Number of parameters = 1,147,524


Epoch 0
Loss = 1.0795e+02, PNorm = 44.7761, GNorm = 498.2163, lr_0 = 1.9014e-04, lr_1 = 1.9014e-04, lr_2 = 1.9014e-04
Parameter containing:
tensor([-1.9276, -1.9380, -1.9440, -1.9527, -1.9432, -1.9347, -1.9573, -1.9376,
        -1.9390, -1.9399, -1.9401, -1.9390], requires_grad=True)
Validation mae = 15.306404
Epoch 1
Loss = 4.0580e+01, PNorm = 44.2114, GNorm = 793.2010, lr_0 = 2.8014e-04, lr_1 = 2.8014e-04, lr_2 = 2.8014e-04
Parameter containing:
tensor([-1.8297, -1.8653, -1.8630, -1.8955, -1.8708, -1.8625, -1.8987, -1.8596,
        -1.8624, -1.8646, -1.8648, -1.8631], requires_grad=True)
Validation mae = 14.088319
Epoch 2
Loss = 2.2387e+01, PNorm = 43.7801, GNorm = 287.0897, lr_0 = 3.7014e-04, lr_1 = 3.7014e-04, lr_2 = 3.7014e-04
Parameter containing:
tensor([-1.7101, -1.7715, -1.7593, -1.8296, -1.7830, -1.7704, -1.8195, -1.7579,
        -1.7632, -1.7664, -1.7661, -1.7639], requires_grad=True)
Validation mae = 11.727799
Epoch 3
Loss = 9.8405e+00, PNorm = 43.1617, GNorm = 128.8608, lr

Validation mae = 4.762852
Epoch 27
Loss = -1.0616e+01, PNorm = 27.5226, GNorm = 38.6705, lr_0 = 8.6681e-04, lr_1 = 8.6681e-04, lr_2 = 8.6681e-04
Parameter containing:
tensor([-0.5441, -1.4474, -1.0712, -1.5605, -1.3434, -1.2458, -1.7042, -1.3618,
        -1.5976, -1.5976, -1.5977, -1.5976], requires_grad=True)
Validation mae = 5.153545
Epoch 28
Loss = -1.0445e+01, PNorm = 27.7095, GNorm = 40.2052, lr_0 = 8.5996e-04, lr_1 = 8.5996e-04, lr_2 = 8.5996e-04
Parameter containing:
tensor([-0.5548, -1.4304, -1.0680, -1.5484, -1.3194, -1.2475, -1.6948, -1.3442,
        -1.5775, -1.5775, -1.5775, -1.5775], requires_grad=True)
Validation mae = 5.529628
Epoch 29
Loss = -1.0823e+01, PNorm = 27.7465, GNorm = 23.1730, lr_0 = 8.5316e-04, lr_1 = 8.5316e-04, lr_2 = 8.5316e-04
Parameter containing:
tensor([-0.5645, -1.4462, -1.0572, -1.5675, -1.3526, -1.2638, -1.6917, -1.3465,
        -1.5845, -1.5845, -1.5844, -1.5845], requires_grad=True)
Validation mae = 4.526056
Epoch 30
Loss = -1.0956e+01, PNorm = 2

Validation mae = 4.083056
Epoch 54
Loss = -1.2253e+01, PNorm = 27.7183, GNorm = 81.2527, lr_0 = 6.9956e-04, lr_1 = 6.9956e-04, lr_2 = 6.9956e-04
Parameter containing:
tensor([-0.5846, -1.5869, -1.1118, -1.6350, -1.4105, -1.3495, -1.8355, -1.4886,
        -1.7876, -1.7876, -1.7876, -1.7875], requires_grad=True)
Validation mae = 4.060757
Epoch 55
Loss = -1.2347e+01, PNorm = 27.6687, GNorm = 43.0234, lr_0 = 6.9402e-04, lr_1 = 6.9402e-04, lr_2 = 6.9402e-04
Parameter containing:
tensor([-0.5831, -1.6031, -1.1325, -1.6523, -1.4297, -1.3622, -1.8526, -1.5056,
        -1.8002, -1.8002, -1.8002, -1.8002], requires_grad=True)
Validation mae = 4.249018
Epoch 56
Loss = -1.1927e+01, PNorm = 27.9232, GNorm = 70.0703, lr_0 = 6.8853e-04, lr_1 = 6.8853e-04, lr_2 = 6.8853e-04
Parameter containing:
tensor([-0.5926, -1.5686, -1.1357, -1.6251, -1.4271, -1.3293, -1.8029, -1.4574,
        -1.7582, -1.7582, -1.7582, -1.7582], requires_grad=True)
Validation mae = 4.447180
Epoch 57
Loss = -1.2294e+01, PNorm = 2

Validation mae = 3.548776
Epoch 81
Loss = -1.3112e+01, PNorm = 27.7282, GNorm = 31.7045, lr_0 = 5.6457e-04, lr_1 = 5.6457e-04, lr_2 = 5.6457e-04
Parameter containing:
tensor([-0.6078, -1.6699, -1.1689, -1.6887, -1.4750, -1.3962, -1.9102, -1.5632,
        -1.9134, -1.9134, -1.9134, -1.9134], requires_grad=True)
Validation mae = 3.677309
Epoch 82
Loss = -1.3014e+01, PNorm = 27.9782, GNorm = 60.3366, lr_0 = 5.6011e-04, lr_1 = 5.6011e-04, lr_2 = 5.6011e-04
Parameter containing:
tensor([-0.5947, -1.6632, -1.1748, -1.6903, -1.4729, -1.3958, -1.9111, -1.5552,
        -1.9016, -1.9016, -1.9016, -1.9015], requires_grad=True)
Validation mae = 3.567980
Epoch 83
Loss = -1.3006e+01, PNorm = 27.8877, GNorm = 68.7400, lr_0 = 5.5568e-04, lr_1 = 5.5568e-04, lr_2 = 5.5568e-04
Parameter containing:
tensor([-0.5973, -1.6619, -1.1724, -1.6895, -1.4740, -1.3957, -1.9080, -1.5518,
        -1.8979, -1.8979, -1.8979, -1.8979], requires_grad=True)
Validation mae = 4.120882
Epoch 84
Loss = -1.3276e+01, PNorm = 2

Validation mae = 3.446834
Epoch 108
Loss = -1.3888e+01, PNorm = 27.8401, GNorm = 26.1647, lr_0 = 4.5563e-04, lr_1 = 4.5563e-04, lr_2 = 4.5563e-04
Parameter containing:
tensor([-0.6154, -1.7305, -1.2154, -1.7239, -1.5189, -1.4414, -1.9697, -1.6109,
        -1.9957, -1.9957, -1.9957, -1.9957], requires_grad=True)
Validation mae = 3.275311
Epoch 109
Loss = -1.3877e+01, PNorm = 27.7292, GNorm = 44.3578, lr_0 = 4.5203e-04, lr_1 = 4.5203e-04, lr_2 = 4.5203e-04
Parameter containing:
tensor([-0.6177, -1.7366, -1.2026, -1.7343, -1.5239, -1.4451, -1.9694, -1.6168,
        -1.9991, -1.9991, -1.9991, -1.9991], requires_grad=True)
Validation mae = 3.410044
Epoch 110
Loss = -1.3913e+01, PNorm = 27.7594, GNorm = 98.2637, lr_0 = 4.4845e-04, lr_1 = 4.4845e-04, lr_2 = 4.4845e-04
Parameter containing:
tensor([-0.6174, -1.7422, -1.2097, -1.7337, -1.5285, -1.4433, -1.9766, -1.6181,
        -2.0030, -2.0030, -2.0030, -2.0030], requires_grad=True)
Validation mae = 3.782281
Epoch 111
Loss = -1.4038e+01, PNorm

Validation mae = 3.267104
Epoch 135
Loss = -1.4579e+01, PNorm = 27.5062, GNorm = 43.6207, lr_0 = 3.6772e-04, lr_1 = 3.6772e-04, lr_2 = 3.6772e-04
Parameter containing:
tensor([-0.6277, -1.7969, -1.2362, -1.7610, -1.5523, -1.4722, -2.0163, -1.6683,
        -2.0870, -2.0871, -2.0871, -2.0870], requires_grad=True)
Validation mae = 3.233440
Epoch 136
Loss = -1.4624e+01, PNorm = 27.4661, GNorm = 29.9086, lr_0 = 3.6481e-04, lr_1 = 3.6481e-04, lr_2 = 3.6481e-04
Parameter containing:
tensor([-0.6281, -1.8026, -1.2309, -1.7645, -1.5579, -1.4713, -2.0224, -1.6700,
        -2.0943, -2.0943, -2.0943, -2.0943], requires_grad=True)
Validation mae = 3.255144
Epoch 137
Loss = -1.4291e+01, PNorm = 27.5160, GNorm = 38.4552, lr_0 = 3.6192e-04, lr_1 = 3.6192e-04, lr_2 = 3.6192e-04
Parameter containing:
tensor([-0.6304, -1.7968, -1.2306, -1.7558, -1.5516, -1.4735, -2.0175, -1.6632,
        -2.0843, -2.0844, -2.0844, -2.0843], requires_grad=True)
Validation mae = 3.386831
Epoch 138
Loss = -1.4509e+01, PNorm

Validation mae = 3.268475
Epoch 162
Loss = -1.5013e+01, PNorm = 27.2457, GNorm = 44.8886, lr_0 = 2.9676e-04, lr_1 = 2.9676e-04, lr_2 = 2.9676e-04
Parameter containing:
tensor([-0.6370, -1.8323, -1.2583, -1.7841, -1.5780, -1.4970, -2.0518, -1.6921,
        -2.1514, -2.1514, -2.1514, -2.1514], requires_grad=True)
Validation mae = 3.387653
Epoch 163
Loss = -1.5065e+01, PNorm = 27.1912, GNorm = 45.1020, lr_0 = 2.9442e-04, lr_1 = 2.9442e-04, lr_2 = 2.9442e-04
Parameter containing:
tensor([-0.6351, -1.8365, -1.2573, -1.7744, -1.5783, -1.4991, -2.0533, -1.6971,
        -2.1556, -2.1557, -2.1557, -2.1556], requires_grad=True)
Validation mae = 3.239756
Epoch 164
Loss = -1.4941e+01, PNorm = 27.1910, GNorm = 43.9201, lr_0 = 2.9209e-04, lr_1 = 2.9209e-04, lr_2 = 2.9209e-04
Parameter containing:
tensor([-0.6368, -1.8325, -1.2579, -1.7813, -1.5819, -1.5007, -2.0523, -1.6946,
        -2.1547, -2.1547, -2.1547, -2.1547], requires_grad=True)
Validation mae = 3.291991
Epoch 165
Loss = -1.5084e+01, PNorm

Validation mae = 3.651795
Epoch 189
Loss = -1.5310e+01, PNorm = 26.9445, GNorm = 91.0055, lr_0 = 2.3950e-04, lr_1 = 2.3950e-04, lr_2 = 2.3950e-04
Parameter containing:
tensor([-0.6485, -1.8670, -1.2768, -1.8079, -1.6093, -1.5199, -2.0834, -1.7314,
        -2.2035, -2.2035, -2.2035, -2.2035], requires_grad=True)
Validation mae = 3.099652
Epoch 190
Loss = -1.5451e+01, PNorm = 26.9177, GNorm = 41.1606, lr_0 = 2.3761e-04, lr_1 = 2.3761e-04, lr_2 = 2.3761e-04
Parameter containing:
tensor([-0.6503, -1.8674, -1.2772, -1.8063, -1.6080, -1.5224, -2.0850, -1.7319,
        -2.2035, -2.2035, -2.2035, -2.2035], requires_grad=True)
Validation mae = 3.208051
Epoch 191
Loss = -1.5416e+01, PNorm = 26.8944, GNorm = 60.8337, lr_0 = 2.3573e-04, lr_1 = 2.3573e-04, lr_2 = 2.3573e-04
Parameter containing:
tensor([-0.6507, -1.8699, -1.2807, -1.8128, -1.6124, -1.5214, -2.0889, -1.7328,
        -2.2065, -2.2065, -2.2065, -2.2065], requires_grad=True)
Validation mae = 3.090733
Epoch 192
Loss = -1.5470e+01, PNorm

Validation mae = 2.859998
Epoch 216
Loss = -1.5827e+01, PNorm = 26.6402, GNorm = 38.1529, lr_0 = 1.9329e-04, lr_1 = 1.9329e-04, lr_2 = 1.9329e-04
Parameter containing:
tensor([-0.6578, -1.8972, -1.3048, -1.8270, -1.6319, -1.5395, -2.1156, -1.7603,
        -2.2442, -2.2442, -2.2442, -2.2442], requires_grad=True)
Validation mae = 2.952284
Epoch 217
Loss = -1.5739e+01, PNorm = 26.6362, GNorm = 57.5449, lr_0 = 1.9176e-04, lr_1 = 1.9176e-04, lr_2 = 1.9176e-04
Parameter containing:
tensor([-0.6574, -1.8961, -1.3067, -1.8286, -1.6349, -1.5394, -2.1149, -1.7602,
        -2.2452, -2.2453, -2.2453, -2.2452], requires_grad=True)
Validation mae = 3.132512
Epoch 218
Loss = -1.5689e+01, PNorm = 26.6495, GNorm = 47.7083, lr_0 = 1.9024e-04, lr_1 = 1.9024e-04, lr_2 = 1.9024e-04
Parameter containing:
tensor([-0.6557, -1.8961, -1.3041, -1.8288, -1.6329, -1.5394, -2.1140, -1.7593,
        -2.2456, -2.2456, -2.2456, -2.2456], requires_grad=True)
Validation mae = 2.908170
Epoch 219
Loss = -1.5679e+01, PNorm

Process Process-3538:
Process Process-3541:
Process Process-3539:
Process Process-3537:
Process Process-3543:
Process Process-3542:
Process Process-3540:
Process Process-3544:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Applications/anaconda3/lib/python3.7/multiprocessing/process.py", line 300, in _bootstrap
    util._exit_function()
  File "/Applications/anaconda3/lib/python3.7/multiprocessing/process.py", line 300, in _bootstrap
    util._exit_function()
  File "/Applications/anaconda3/lib/python3.7/multiprocessing/process.py", line 300, in _bootstrap
    util._exit_function()
  File "/Applications/anaconda3/lib/python3.7/multiprocessing/process.py", line 300, in _bootstrap
    util._exit_function()
  File "/Applications/anaconda3/lib/python3.

KeyboardInterrupt: 

Weight decay of 0.01

In [5]:
args.weight_decay = 0.01
results_MAP = run_training(args)

5903it [00:00, 59027.10it/s]

Command line
python /Applications/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py -f /Users/georgelamb/Library/Jupyter/runtime/kernel-3ce28114-5e5a-455d-a29b-0c200a224367.json
Args
{'activation': 'ReLU',
 'atom_messages': False,
 'batch_size_gp': 100,
 'batch_size_sgld': 50,
 'bbp': False,
 'bias': False,
 'block': True,
 'burnin_epochs': 10,
 'c_swag': 0,
 'cache_cutoff': 10000,
 'class_balance': False,
 'config_path': None,
 'cov_mat': False,
 'crossval_index_dir': None,
 'crossval_index_file': None,
 'crossval_index_sets': None,
 'data_path': '/Users/georgelamb/Documents/GitHub/chempropBayes/data/QM9.csv',
 'dataset_type': 'regression',
 'depth': 5,
 'dropout': 0.0,
 'dropout_FFNonly': False,
 'ensemble_size': 1,
 'epochs': 100,
 'epochs_gp': 100,
 'epochs_swag': 0,
 'features_generator': None,
 'features_only': False,
 'features_path': None,
 'features_size': None,
 'ffn_hidden_size': 500,
 'ffn_num_layers': 3,
 'final_lr': 0.0001,
 'final_lr_gp': 0.0001,
 'folds_file':

49476it [00:00, 88270.38it/s]
  4%|▍         | 1991/50000 [00:00<00:02, 19900.06it/s]

Number of tasks = 12
Splitting data with seed 0


100%|██████████| 50000/50000 [00:04<00:00, 11510.29it/s]


Total size = 50,000 | train size = 32,000 | val size = 8,000 | test size = 10,000
Fitting scaler
Building model 0
MoleculeModel(
  (encoder): MPN(
    (encoder): MPNEncoder(
      (dropout_layer): Dropout(p=0.0, inplace=False)
      (act_func): ReLU()
      (W_i): Linear(in_features=147, out_features=500, bias=False)
      (W_h): Linear(in_features=500, out_features=500, bias=False)
      (W_o): Linear(in_features=633, out_features=500, bias=True)
    )
  )
  (ffn): Sequential(
    (0): Dropout(p=0.0, inplace=False)
    (1): Linear(in_features=500, out_features=500, bias=True)
    (2): ReLU()
    (3): Dropout(p=0.0, inplace=False)
    (4): Linear(in_features=500, out_features=500, bias=True)
    (5): ReLU()
    (6): Dropout(p=0.0, inplace=False)
    (7): Linear(in_features=500, out_features=12, bias=True)
  )
)
Number of parameters = 1,147,524
Epoch 0
Loss = 1.5944e+00, PNorm = 41.9207, GNorm = 661.8070, lr_0 = 5.5070e-04, lr_1 = 5.5070e-04, lr_2 = 5.5070e-04
Parameter containing:
tens

Validation mae = 3.665068
Epoch 24
Loss = -3.2856e-01, PNorm = 27.1110, GNorm = 59.0229, lr_0 = 5.8249e-04, lr_1 = 5.8249e-04, lr_2 = 5.8249e-04
Parameter containing:
tensor([-0.7251, -1.9034, -1.3880, -2.0041, -1.7145, -1.6125, -2.3558, -1.8251,
        -2.0819, -2.0811, -2.0809, -2.0811], requires_grad=True)
Validation mae = 3.617521
Epoch 25
Loss = -3.0456e-01, PNorm = 27.6068, GNorm = 59.5624, lr_0 = 5.6897e-04, lr_1 = 5.6897e-04, lr_2 = 5.6897e-04
Parameter containing:
tensor([-0.7089, -1.8806, -1.3593, -1.9620, -1.6813, -1.5939, -2.3448, -1.7998,
        -2.0586, -2.0576, -2.0574, -2.0573], requires_grad=True)
Validation mae = 4.015478
Epoch 26
Loss = -3.3729e-01, PNorm = 27.1543, GNorm = 95.2865, lr_0 = 5.5575e-04, lr_1 = 5.5575e-04, lr_2 = 5.5575e-04
Parameter containing:
tensor([-0.7279, -1.9261, -1.4002, -2.0273, -1.7368, -1.6262, -2.3813, -1.8483,
        -2.1037, -2.1030, -2.1027, -2.1026], requires_grad=True)
Validation mae = 3.715247
Epoch 27
Loss = -3.3862e-01, PNorm = 2

Validation mae = 2.985512
Epoch 51
Loss = -4.0177e-01, PNorm = 27.3235, GNorm = 44.9888, lr_0 = 3.0887e-04, lr_1 = 3.0887e-04, lr_2 = 3.0887e-04
Parameter containing:
tensor([-0.8668, -2.2717, -1.6524, -2.3054, -2.0299, -1.8661, -2.7438, -2.1720,
        -2.4967, -2.4966, -2.4964, -2.4961], requires_grad=True)
Validation mae = 2.935012
Epoch 52
Loss = -4.2389e-01, PNorm = 27.3111, GNorm = 75.7853, lr_0 = 3.0170e-04, lr_1 = 3.0170e-04, lr_2 = 3.0170e-04
Parameter containing:
tensor([-0.8751, -2.2896, -1.6673, -2.3241, -2.0451, -1.8766, -2.7590, -2.1882,
        -2.5195, -2.5194, -2.5193, -2.5190], requires_grad=True)
Validation mae = 3.132162
Epoch 53
Loss = -4.2266e-01, PNorm = 27.2690, GNorm = 99.5230, lr_0 = 2.9469e-04, lr_1 = 2.9469e-04, lr_2 = 2.9469e-04
Parameter containing:
tensor([-0.8813, -2.3048, -1.6825, -2.3426, -2.0573, -1.8873, -2.7718, -2.2012,
        -2.5377, -2.5376, -2.5376, -2.5373], requires_grad=True)
Validation mae = 2.795774
Epoch 54
Loss = -4.1519e-01, PNorm = 2

Validation mae = 2.658275
Epoch 78
Loss = -4.7511e-01, PNorm = 27.2950, GNorm = 79.9496, lr_0 = 1.6378e-04, lr_1 = 1.6378e-04, lr_2 = 1.6378e-04
Parameter containing:
tensor([-0.9967, -2.5206, -1.9281, -2.6003, -2.3556, -2.0758, -2.9673, -2.4052,
        -2.7859, -2.7859, -2.7859, -2.7857], requires_grad=True)
Validation mae = 2.535998
Epoch 79
Loss = -4.7867e-01, PNorm = 27.2811, GNorm = 95.4715, lr_0 = 1.5998e-04, lr_1 = 1.5998e-04, lr_2 = 1.5998e-04
Parameter containing:
tensor([-1.0019, -2.5263, -1.9409, -2.6121, -2.3712, -2.0831, -2.9726, -2.4113,
        -2.7923, -2.7923, -2.7923, -2.7922], requires_grad=True)
Validation mae = 2.569717
Epoch 80
Loss = -4.8160e-01, PNorm = 27.2778, GNorm = 75.1990, lr_0 = 1.5626e-04, lr_1 = 1.5626e-04, lr_2 = 1.5626e-04
Parameter containing:
tensor([-1.0047, -2.5323, -1.9488, -2.6241, -2.3833, -2.0898, -2.9779, -2.4173,
        -2.7990, -2.7990, -2.7990, -2.7988], requires_grad=True)
Validation mae = 2.513182
Epoch 81
Loss = -4.7210e-01, PNorm = 2